// controllers
export * from "./controllers/mainController"
export * from "./controllers/canvasController"
export * from "./controllers/eraseController"
export * from "./controllers/exportController"
export * from "./controllers/saveController"
export * from "./controllers/importController"
export * from "./controllers/importReportController"
export * from "./import/aiRepair"
export * from "./import/diagnostics"
export * from "./import/jsonImporter"
export * from "./import/applyImportResult"
export * from "./import/tikzLexer"
export * from "./import/tikzParser"
export * from "./import/tikzTransformer"
export * from "./controllers/selectionController"
export * from "./controllers/undoController"
export * from "./controllers/copyController"
export * from "./controllers/propertiesController"
export * from "./controllers/environmentVariableController"
export * from "./controllers/themeController"
export * from "./controllers/commandPaletteController"
export * from "./controllers/shortcutsController"
export * from "./i18n"
// properties
export * from "./properties/editableProperty"
export * from "./properties/booleanProperty"
export * from "./properties/choiceProperty"
export * from "./properties/textProperty"
export * from "./properties/textAreaProperty"
export * from "./properties/infoProperty"
export * from "./properties/buttonGridProperty"
export * from "./properties/mathjaxProperty"
export * from "./properties/sliderProperty"
export * from "./properties/sectionHeaderProperty"
export * from "./properties/colorProperty"
export * from "./properties/radioButtonProperty"
//mixins
export * from "./mixins/fillable"
export * from "./mixins/strokable"
export * from "./mixins/nameable"
export * from "./mixins/labelable"
export * from "./mixins/voltageable"
export * from "./mixins/currentable"
// components
export * from "./components/circuitComponent"
export * from "./components/pathComponent"
export * from "./components/nodeComponent"
export * from "./components/componentPlacer"
export * from "./components/componentSymbol"
export * from "./components/nodeSymbolComponent"
export * from "./components/pathSymbolComponent"
export * from "./components/wireComponent"
export * from "./components/shapeComponent"
export * from "./components/rectangleComponent"
export * from "./components/ellipseComponent"
export * from "./components/polygonComponent"
export * from "./components/splineComponent"
export * from "./components/groupComponent"
export * from "./components/shortComponent"
export * from "./components/openComponent"
export * from "./components/rotateFlipGrid"
// snapDrag
export * from "./snapDrag/dragHandlers"
export * from "./snapDrag/snapController"
export * from "./snapDrag/snapCursor"
export * from "./snapDrag/snapPoint"
// other
export * from "./utils/textHelper"
export * from "./utils/utils"
export * from "./utils/tikzBuilder"
// vision (handwritten circuit detection)
export * from "./vision/visionProvider"
export * from "./vision/visionError"
export * from "./vision/detectionTypes"
export * from "./vision/prompts/componentVocabulary"
export * from "./vision/prompts/detectionSchema"
export * from "./vision/prompts/detectionPrompt"
export * from "./vision/pipeline/confidenceClassifier"
export * from "./vision/pipeline/imagePreprocessor"
export * from "./vision/pipeline/detectionResultMapper"
export * from "./vision/storage/providerStorage"
export * from "./vision/providers/openaiCompatProvider"
export * from "./vision/providers/anthropicProvider"
export * from "./vision/providers/geminiProvider"
export * from "./vision/controllers/confidenceOverlayController"
export * from "./vision/controllers/reviewChipController"
export * from "./vision/controllers/visionSettingsController"
export * from "./vision/controllers/visionImportController"
// Must come after the property/canvas modules above; depends on BooleanProperty, SliderProperty, etc.
export * from "./controllers/viewPropertiesController"

// cleanup-audit additions (I3, I4)
export * from "./mixins/colorOpacityPair"
export * from "./utils/arrowConstants"

// v1.1 UX additions (top-bar dropdowns, version label, onboarding toast,
// shortcut overlay, AI provider chips). Append-only; safe to remove if the
// V1.1 polish layer is ever rolled back.
export * from "./controllers/uxV11Controller"
